### ISSUE TITLE
RFC 2544 benchmarking IP addresses should be considered private

### ISSUE THREAD

**Issue by kdrag0n** [WICG/local-network-access#104]
The `198.18.0.0/15` benchmarking IP range reserved by [RFC 2544](https://www.rfc-editor.org/rfc/rfc2544) is not globally routable, so it should be considered private similar to the logic for CGNAT (`100.64.0.0/10`) in #92. The more recent [RFC 6890](https://www.rfc-editor.org/rfc/rfc6890) confirms that this range is still reserved, and it's also marked as not globally routable in the [IANA IPv4 Special-Purpose Address Registry](https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml).

We're considering using this as a low-conflict private IP range for a use case where traffic never leaves the same physical machine. It'd be great if the range could be added to PNA in order to protect local services running within the subnet.

Happy to make a pull request if the idea is accepted.

**Comment by letitz** [comment]
That seems reasonable to me. Can you send a PR?

**Comment by kdrag0n** [comment]
Done, thanks for looking at this!
