### ISSUE TITLE
Could this new step in CORS preflight not be carried out earlier?

### ISSUE THREAD

**Issue by jub0bs** [WICG/local-network-access#86]
In [section 3.1.2.](https://wicg.github.io/private-network-access/#cors-preflight) (entitled _CORS preflight_), item 4.2 reads as follows (please ignore the difference in numbering format):

> 2. **Immediately after checking CORS-unsafe request-header names in response against request’s header list**:
>     1. If request’s target IP address space is not null, then:
>         1. Let allow be the result of extracting header list values given "Access-Control-Allow-Private-Network" and response’s header list.
>         2. If allow is not "true", return a network error.

(my emphasis)

Is there a reason this step comes "so" late? For performance reasons, could that step not be moved, for instance, to immediately after the [CORS check](https://fetch.spec.whatwg.org/#concept-cors-check) that takes place at step 7 of [CORS-preflight fetch](https://fetch.spec.whatwg.org/#cors-preflight-fetch-0)?

**Comment by jub0bs** [comment]
@letitz For context, my line of thought was that processing the ACAM and ACAH headers can potentially be costly (e.g. if the server responds with long header values). We could potentially cut down on all that work if the request's issuing origin resolves to a less private network and the server hasn't allowed PNA.

**Comment by letitz** [comment]
Fair enough! Would you care to send a PR?

**Comment by letitz** [comment]
Great, thanks!

**Comment by letitz** [comment]
This should have been closed when #90 was merged.

**Comment by jub0bs** [comment]
@letitz Weird, I thought I had left a comment on this... Anyway, have you created a crbug to track this change in Chromium? One reason I'm asking is that maintainers of CORS middleware may accordingly want to adjust the order in which they check things.

**Comment by letitz** [comment]
I was also briefly confused, having déjà vu... It's because you left the comment and I replied on the PR (#90)!

**Comment by jub0bs** [comment]
@letitz Sorry! All good.
